export const SANITIZE_OPTION = {
  allowedTags: [
    "p",
    "span",
    "ol",
    "ul",
    "li",
    "br",
    "strong",
    "em",
    "u",
    "s",
    "blockquote",
    "pre",
    "a",
    "img",
    "iframe",
  ],
  allowedAttributes: {
    p: ["class", "style"],
    span: ["class", "style"],
    ol: ["class", "style"],
    ul: ["class", "style", "data-checked"],
    li: ["class", "style"],
    strong: ["class", "style"],
    em: ["class", "style"],
    u: ["class", "style"],
    s: ["class", "style"],
    blockquote: ["class", "style"],
    pre: ["class", "style", "spellcheck"],
    a: ["class", "style", "href", "rel", "target", "style"],
    img: ["class", "style", "src", "width"],
    iframe: ["class", "style", "frameborder", "allowfullscreen", "src"],
  },
  allowedSchemes: ["data", "http", "https"],
} as const;
