export const FEELING_STATUS: Record<string, string> = {
  1: "EXCITED",
  2: "NICE",
  3: "SOSO",
  4: "SAD",
  5: "ANGRY",
  EXCITED: "1",
  NICE: "2",
  SOSO: "3",
  SAD: "4",
  ANGRY: "5",
  최고: "1",
  좋아: "2",
  무난: "3",
  슬퍼: "4",
  화나: "5",
} as const;
